URL: https://www.fengmap.com
log:
    file_name: test.log.2018-5-15
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
ip: 127.0.0.1
port: 8080
